import requests
from pytorrent.bencode import Bencoder


def request_tracker(info_hash, peer_id, tracker_url):
    """requests the tracker server to get the details of the torrent

    Args:
        info_hash(String): hash of the info dict on metainfo,
        peer_id(String): 20 byte client id generated by client
        tracker_url(String): http announce parameter present in metainfo
                             file

    Returns:
        dict: response of the request

    """

    payload = {"info_hash": info_hash,
               "peer_id": peer_id,
               "port": 6881,
               "uploaded": 0,
               "downloaded": 0,
               "left": 1000,
               "compact": 1}

    response = requests.get(tracker_url, params=payload)
    return Bencoder.decode(response.content)
